# Generated by Django 3.0.3 on 2020-02-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='grading.Subject'),
        ),
    ]
