# Generated by Django 3.0.3 on 2020-03-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Ave',
            field=models.IntegerField(null=True, verbose_name=range(70, 95)),
        ),
        migrations.AddField(
            model_name='student',
            name='FirstSemFinals',
            field=models.IntegerField(null=True, verbose_name=range(70, 95)),
        ),
        migrations.AddField(
            model_name='student',
            name='FirstSemMidTerms',
            field=models.IntegerField(null=True, verbose_name=range(70, 95)),
        ),
        migrations.AddField(
            model_name='student',
            name='SecondSemMidTerms',
            field=models.IntegerField(null=True, verbose_name=range(70, 95)),
        ),
        migrations.AddField(
            model_name='student',
            name='SecondSemfinals',
            field=models.IntegerField(null=True, verbose_name=range(70, 95)),
        ),
        migrations.AlterField(
            model_name='student',
            name='grades',
            field=models.IntegerField(null=True, verbose_name=range(70, 95)),
        ),
    ]
