# Generated by Django 3.0.3 on 2020-03-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
        ('users', '0002_auto_20200303_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='grading.Subject'),
        ),
    ]
