# Generated by Django 3.0.3 on 2020-02-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_grade'),
        ('users', '0003_auto_20200223_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ManyToManyField(to='grading.Grade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grade',
            field=models.ManyToManyField(to='grading.Grade'),
        ),
    ]
