# Generated by Django 3.0.3 on 2020-02-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_grade'),
        ('users', '0004_auto_20200223_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='grading.Subject'),
        ),
    ]
