# Generated by Django 3.0.3 on 2020-02-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200226_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.DecimalField(decimal_places=2, default='0.0000', max_digits=100),
        ),
    ]
