# Generated by Django 3.0.3 on 2020-03-03 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200303_0532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grades',
        ),
    ]
