# Generated by Django 3.0.3 on 2020-03-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200303_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='teacher',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.Teacher'),
            preserve_default=False,
        ),
    ]
