# Generated by Django 3.0.3 on 2020-03-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200303_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(max_length=10),
        ),
    ]
