# Generated by Django 3.0.3 on 2020-03-05 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200305_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
