# Generated by Django 3.0.3 on 2020-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubject',
            name='FSFgrades',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='FSMTgrades',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='FSgrades',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='SFgrades',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='SSFgrades',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubject',
            name='SSMTgrades',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
