# Generated by Django 3.0.3 on 2020-02-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200226_1115'),
        ('grading', '0002_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
